# Generated by Django 5.0.2 on 2024-03-03 15:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('meeting_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('users', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'ordering': ['-meeting_time'],
                'indexes': [models.Index(fields=['meeting_time'], name='meeting_time_index')],
            },
        ),
    ]
