# Generated by Django 5.0.1 on 2024-01-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag_note_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['mode_time']},
        ),
        migrations.AlterField(
            model_name='note',
            name='mode_time',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['mode_time'], name='mode_at_index'),
        ),
    ]
