# Generated by Django 5.0.1 on 2024-01-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='count_KKal',
            field=models.CharField(default=1, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(null=True, verbose_name='describtion of ingredient'),
        ),
    ]
